---
abstract: 'Minimal but customizable logger.'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Minimal
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Log::Minimal:
    file: lib/Log/Minimal.pm
    version: 0.16
requires:
  Data::Dumper: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
resources:
  bugtracker: https://github.com/kazeburo/Log-Minimal/issues
  homepage: https://github.com/kazeburo/Log-Minimal
  repository: git://github.com/kazeburo/Log-Minimal.git
version: 0.16
x_contributors:
  - 'sugyan <sugi1982@gmail.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
